# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'rowalter.github.io'
baseurl: ''
title: 'rowalter.github.io'
description: 'This is my website'
permalink: pretty
logo: "/images/site/avatar.jpg"

# GEM Settings
paginate: 5
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com 
twitter:
  username: rowalter_vmw
author: Robert Walter 
social: 
  name: Robert Walter 
  links:  
    - https://twitter.com/rowalter_vmw

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/rowalter_vmw

sharing_links:
  Twitter: true
  Email: true

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My ideas and little projects"
    feature_text: |
      ## Robert Walter
    feature_image: "/images/site/23225.jpg"
